const teamData= {
    Minhaz_Nawas: require('../images/team_photos/Minhaz_Nawas.jpg'),
    Akhil_antony: require('../images/team_photos/ANTONY SEBASTIAN.jpg'),
    MD_Adil: require('../images/team_photos/ADIL SALFI.jpeg'),
    sreejith: require('../images/team_photos/Sreejith R R.jpg'),
    harish: require('../images/team_photos/Harish Madireddi.jpeg'),
    aman: require('../images/team_photos/Aman Jagtap.webp'),
    mayuri: require('../images/team_photos/Mayuri_chourasia  Rajesh.jpg'),
    rishi: require('../images/team_photos/Ravulapelly Rishi Kumar.jpg'),
    Diva: require('../images/team_photos/Diva Jaiwar.jpg'),
    manikanta: require('../images/team_photos/Uppulapu Manikanta.jpg'),
    mayur: require('../images/team_photos/MAYUR JAGALPURE MANOJ.jpg'),
    pradeep: require('../images/team_photos/Pradeep Mundlik.jpg'),
    stephen: require('../images/team_photos/STEPHEN V S.jpg'),
    sreevani: require('../images/team_photos/CHIKKALAWAR SREEVANI.jpg'),
    anurag: require('../images/team_photos/MANDA ANURAG.jpg'),
    sujith: require('../images/team_photos/Sai Sujith Reddy Sandhi.jpg'),
    riyaann: require('../images/team_photos/Riya Ann Easow.jpeg'),
    bharath: require('../images/team_photos/Chamarthi Bharath.jpg'),
    shravya: require('../images/team_photos/KUMMARI SHRAVYA.jpg'),
    akshat: require('../images/team_photos/Akshat Jain.jpg'),
    kartik: require('../images/team_photos/Kartik Agrawal.jpeg'),
    hiya: require('../images/team_photos/Hiya Mehta.jpg'),
    vishwajith: require('../images/team_photos/Bommineni Vishwajith Reddy.jpg'),
    dhatri: require('../images/team_photos/Velma Dhatri Reddy.jpeg'),
    harishankar: require('../images/team_photos/Harishankar - Harishankar M.jpeg'),
    sreeya: require('../images/team_photos/sreeya - TIPIRISETTY SREEYA.jpeg'),
    pushkal: require('../images/team_photos/Pushkal Mishra.jpg'),
    govind: require('../images/team_photos/Govind Pal.jpg'),
    viren: require('../images/team_photos/Viren.jpeg'),
    rishit: require('../images/team_photos/RISHIT SINGH SOMVANSHI.jpg'),
    siriS: require('../images/team_photos/Siri Shankarathota.jpg'),
    pragya: require('../images/team_photos/Pragya Yadav.jpg'),
    adheena: require('../images/team_photos/Adheena S.jpg'),
    chaitanya: require('../images/team_photos/Malakala Chaitanya.jpeg'),
    loukik: require('../images/team_photos/Loukik Pradip Kalbande.jpg'),
    gatikrushna: require('../images/team_photos/Gatikrushna Mohapatra.jpg'),
    aayush: require('../images/team_photos/Aayush_Prabhu.jpg'),
    ajay: require('../images/team_photos/AJAY PATEL.jpg'),
    arun: require('../images/team_photos/RONGALA ARUN SIDDARDHA.jpg'),
    suryaansh: require('../images/team_photos/Suryaansh Jain.jpeg'),
    surya: require('../images/team_photos/SURYA SUDEEP.jpg'),
    ritik: require('../images/team_photos/Ritik Pal.jpg'),
    jashwanth: require('../images/team_photos/Jaswanth beere.jpg'),
    bhanu: require('../images/team_photos/CHEMIKALA BHANU TEJA REDDY.jpeg'),
    ramanathan: require('../images/team_photos/RAMANATHAN ANNAMALAI.jpg'),
    uday: require('../images/team_photos/P Uday Ratna Sekhar.jpg'),
    uttej: require('../images/team_photos/Uttej.png'),
    pranav: require('../images/team_photos/Pericherla Pranav Varma.jpeg'),
    aravind: require('../images/team_photos/Aravind Siddhartha Kotichintala.jpg'),
    sathvika: require('../images/team_photos/Marri Sathvika.jpg'),
    sanaAnesha: require('../images/team_photos/Sana Anesha Shabbeer.jpg'),
    hadiAfnan: require('../images/team_photos/HADI AFNAN.jpg'),
    ahinraj: require('../images/team_photos/AHINRAJ M S.jpg'),
    divyaM: require('../images/team_photos/DIVYA M.jpg'),
    nabeelM: require('../images/team_photos/NABEEL MOHAMMED P T.JPG'),
    //ravindra: require('../images/team_photos/.jpg'),
    BRohit: require('../images/team_photos/Bevara Rohit.jpg'),
    abhishek: require('../images/team_photos/Abhishek Ghosh.jpg'),
    // BAnvitha: require('../images/team_photos/.jpg'),
    shreyas: require('../images/team_photos/Shreyas Rajesh Wankhede.jpeg'),
    shubham: require('../images/team_photos/Subham Mohanty.jpg'),
    suryaTeja: require('../images/team_photos/CHERUKUSURYA TEJA.jpg'),
    dheeraj: require('../images/team_photos/Dheeraj M.jpeg'),
    dhanushikaa: require('../images/team_photos/Dhanushikaa S.jpg'),
    subiksha: require('../images/team_photos/Subiksha Gayathiri K K.jpg'),
    yashRamteke: require('../images/team_photos/Yash Rajesh Ramteke.jpeg'),
    // mouktika: require('../images/team_photos/Cherukupalli Sai Malini Mouktika.jpg'),
    nanda: require('../images/team_photos/Nanda Kishore Reddy Mummadi.jpg'),
    // gaurang: require('../images/team_photos/.jpg'),
    // raniKR: require('../images/team_photos/.jpg'),
    //abhayKumar: require('../images/team_photos/.jpg'),
    //anusha: require('../images/team_photos/.jpg'),
    //rohitS: require('../images/team_photos/.jpg'),
    //krithik: require('../images/team_photos/.jpg'),
    //kaustubh: require('../images/team_photos/.jpg'),
    //jayBhanushali: require('../images/team_photos/.jpg'),
    //kanak: require('../images/team_photos/.jpg'),
    //jalaPrajash: require('../images/team_photos/.jpg'),
}
  

export default teamData;